### ISSUE TITLE
dsPlot on dev (commit removing gca)

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#437]
Commit f70c3b40f746642acfb48a1380cbf0e1ff577fc0 introduced a change in `dsPlot` that was not debugged using the `dsDemos` script. At a minimum, any changes to the code should not break the `dsDemos` script. This must be fixed before merging dev with debug. Also, all changes to dev should be submitted using Pull Requests.

The following error is generated  running the `dsDemos` script:
```
Error using line
Vectors must be the same length.

Error in dsPlot (line 903)
                  line(thisAxes, [spk
                  spk],[c+ypos-.5
                  c+ypos+.5],'color','k'); hold on

Error in dsDemos (line 296)
dsPlot(data,'plot_type','rastergram');
```

A similar error is produced later in `dsDemos`:

```
Error using line
Vectors must be the same length.

Error in dsPlot (line 996)
              line(thisAxes, [vlines(k)
              vlines(k)],ylim,'color','k','linestyle','--'); 
```

**Comment by erik-roberts** [comment]
@jsherfey i don't get this error on my system

**Comment by davestanley** [comment]
> Also, all changes to dev should be submitted using Pull Requests.

Slightly off topic, but since when are we doing this. Does this mean that every single change to dev should be made on its own branch and them submit via pull request? What about minor changes?

**Comment by erik-roberts** [comment]
> Also, all changes to dev should be submitted using Pull Requests.
> 
> Slightly off topic, but since when are we doing this? Does this mean that every single change to dev should be made on its own branch and them submit via pull request? What about minor changes?

yeah this has been tedious.  one quicker solution is to make a branch, then merge directly to dev. then push upstream. this avoids having to do the pull request.  it should look the same from the viewpoint of the git log though. and has the advantage of easier reverting.

**Comment by asoplata** [comment]
Here is sort of our official reference
https://github.com/DynaSim/DynaSim/wiki/Dev-contribution-using-GitHub

**Comment by asoplata** [comment]
Yeah, very minor changes can go directly on-branch to dev or debug (like
bugfixes, config changes with a few lines etc) but most work should be done
on its own branch then merged in. It sounds like Pull Requests for
everything is a little overboard, but doing most development on their own
individual feature branches (with or without Pull Requests) is preferred
and makes the tree much, much easier to comprehend.

**Comment by jsherfey** [comment]
Austin - can you add a summary of our developer guidelines (basically your
earlier message) to the "Dev contribution using GitHub" page. I think you
have the right idea for how we should proceed with collaborative
development. The only caveat I have is that "very minor changes" should be
defined as changes that aren't able to break anything (e.g., changes to
comments). It would be great if you could include an example or two of (1)
minor changes that can be pushed on-branch to dev, (2) major changes that
require their own branch but no PR, (3) major changes that require PR.

**Comment by jsherfey** [comment]
Fixed in Pull Request #443

**Comment by jsherfey** [comment]
This doesn't work in Matlab 2014a now. I received the following error:
```
>> dsDemos
Warning: Directory already exists. 
> In dsDemos at 26 
Error using axes
Too many input arguments.

Error in tight_subplot2 (line 57)
        ha(ii) = axes(hFig, 'Units','normalized', ...

Error in dsPlot (line 497)
        haxes = tight_subplot2(num_rows, num_cols, [.01
        .03], [.05 .01], [.03 .01], thisHandle);

Error in dsDemos (line 132)
dsPlot(data);
```
Also, I'd rather tight_subplot and tight_subplot2 not be in their own subdirectory. This is a minor issue though, and I'm ok with it staying like that if everyone else things it's cleaner. The only problem with it is that it requires updating the Matlab path for tight_subplot2 to be found.

**Comment by kupiqu** [comment]
I think you can workaround the issue as I did for Octave (issue #436), just exclude Matlab versions < 2014b from the same conditional...

**Comment by kupiqu** [comment]
Hopefully fixed with #453

**Comment by jsherfey** [comment]
That did fix the `tight_subplot2` error, but the following error is back in Matlab 2014a and 2017a:
```
Error using line
Vectors must be the same lengths.

Error in dsPlot (line 910)
                  line(thisAxes, [spk spk],[c+ypos-.5
                  c+ypos+.5],'color','k'); hold on

Error in dsDemos (line 296)
dsPlot(data,'plot_type','rastergram'); % <-- Figure 5 in
DynaSim paper
```
