### ISSUE TITLE
covary 2 mechanisms together

### ISSUE THREAD

**Issue by erikthered12** [DynaSim/DynaSim#52]
right now, it seems like one can covary the same mechanism in different populations or connections, but one cannot covary 2 different mechanisms in the same connection/population.  For example, I might want to do: {'E',    ('iNa', 'iK'),    {[1:3], [4:6]}}, so that when na is 1, k is 4 etc. This would be useful for balancing.

another situation is balancing 2 mechanisms in 2 different populations or connections.

**Comment by benpolletta** [comment]
Yeah, I was suggesting this might be useful. Jason, can you point us to
which file we would have to play with to get this to work? Probably
*ApplyModifications*? We just need to have the function parse not only the
parameter names (i.e. if they're a list), but also the parameter ranges
(i.e. if they are also a list).

**Comment by davestanley** [comment]
I think I know the function. I will look it up later today when I'm at a
computer (nudge me if I forget)

**Comment by benpolletta** [comment]
Addressed in commits:
https://github.com/DynaSim/DynaSim/commit/c01797b06e4586ddc6afc5aead619d67e852a442,
https://github.com/DynaSim/DynaSim/commit/1dda6cbaf644ca01bcfd29ecc916f1a03c5f32a2.

**Comment by erikthered12** [comment]
The new method is awesome, thanks Ben!

It still doesn't work with multiple connections though.

**Comment by benpolletta** [comment]
Hey Erik,

Can you give an example of what doesn't work?

B

**Comment by erikthered12** [comment]
Sorry I had a typo, it works fine!

**Comment by erikthered12** [comment]
This is breaking because of the string input:

vary={
    'TC',            'gH',        linspace(0.001, 0.02, 10);
    
    '(RE->RE,TC->RE,RE->TC)',        'prob_cxn',  [0.5, 0.3, 0.1];

    'RE->RE',        'netcon',  'netconNearestNeighbors(Npop*prob_cxn, Npop, true)';
    'TC->RE',        'netcon',  'netconNearestNeighbors(Npop*prob_cxn, Npop, true)';
    'RE->TC',        'netcon',  'netconNearestNeighbors(Npop*prob_cxn, Npop, true)';
  };

Do we want to have support for string inputs like this?

**Comment by benpolletta** [comment]
I assume it's breaking because of the last three lines? I'm confused why
you need to specify those as part of 'vary', when the specification is
identical for all three connections, and could be defined in the mechanism.
Or am I parsing what you've posted incorrectly?

In either case, AFAICT, this ought to be a new issue, about supporting
string inputs into 'vary', unless somehow the covarying in the second line
causes the problem?

**Comment by erikthered12** [comment]
agreed, let's make new issue

**Comment by erikthered12** [comment]
okay, this time I think it's a bug.  When passing the data variable to AnalyzeData, I noticed that both covered variables have the full vector of each other's values.  This doesn't play with with nameFromVaried.  I'm working on fixing this so that each covarried variable gets associated with only its own parameter value.

**Comment by erikthered12** [comment]
i think problem lies in expand_modifications in simulatemodel

**Comment by benpolletta** [comment]
If you get the modification information from a different point in the
program (i.e., after expand_modifications), and then input it to
nameFromVaried, you should have no problem. The output structure should
include somewhere the list of all things varied. Look at the beginning of
PlotData - it receives data.varied (I believe), and each varied variable is
listed separately there. Maybe you can mimic this in nameFromVaried. I'll
take a look, maybe we can talk about this later.

**Comment by erikthered12** [comment]
fixed it, just need to commit it

**Comment by erikthered12** [comment]
fixed with 43d75fb
